version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest

dependencies:
  python:
    - ansible-core>=2.14.0
    - ansible-runner
    - requests
    - netaddr

  system: bindep.txt

additional_build_steps:
  prepend_final:
    - RUN microdnf install -y dnf python3-pip && rm -rf /var/cache
    - RUN pip3 install --extra-index-url=https://ansible.github.io/pylibssh/simple/ --pre ansible-pylibssh==1.2.2

options:
  package_manager_path: /usr/bin/microdnf
