version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest

dependencies:
  python:
    - ansible-core>=2.14.0
    - ansible-runner
    - requests
    - netaddr
    - ansible-pylibssh==1.2.2

  system: bindep.txt

additional_build_steps:
  prepend_final:
    - RUN microdnf install -y dnf && rm -rf /var/cache

options:
  package_manager_path: /usr/bin/microdnf
